<template>
  <v-layout column>
    <v-flex class="row" xs12 v-if="!dismissedChanges">
      <v-card transition="slide-y-transition">
        <v-container>
          <v-layout fill-height>
            <v-flex xs12 align-end flexbox>
              <vue-markdown id="changes-block" :source="changes"></vue-markdown>
            </v-flex>
          </v-layout>
        </v-container>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn @click="dismissChanges()" flat color="primary">Dismiss</v-btn>
        </v-card-actions>
      </v-card>
    </v-flex>
    <v-flex class="row" xs12>
      <h1>Linux Kernel CVEs</h1>
      <p>This is a simple project to track CVEs in the upstream linux kernel. Individual distro’s (RHEL, Debian, Ubuntu, etc) often do a good job of tracking CVEs for their own kernels but this information is lacking for the upstream kernel. This project aims to help out with this void. The output was generated automatically through a set of tools that has not been fully tested or made public yet.</p>
      <h3>Linux security note</h3>
      <p>Tracking, mitigating, and patching CVEs is just a small part of maintaining a secure kernel. Let me be clear, you can patch all known CVEs and still be vulnerable. Some risk can be mitigated through properly configuring your kernel/system. I suggest you visit the Kernel Self Protection Project and other kernel security pages for more information.</p>
      <h3>Reading stream reports</h3>
      <p>Below is a list of definitions for certain strings you might see in a stream report. <strong>The only CVEs that should appear in the stream document are ones that potentially affect that stream.</strong> (ie. ones that were not fixed prior to the first release version and were not introduced after the release version) If no fixing commit is known for a CVE, then by default it is assumed to present in all streams after it was introduced.</p>
      <ul>
        <li>‘Fix unknown’: No fixing commit in the commit maps or the commit is invalid</li>
        <li>‘Fixed with X’: Fixing commit was seen in the stream and first appears in version X</li>
        <li>‘Fix not seen in stream’: The fixing commit is known and valid, but not seen in this stream (ie. stream is still vulnerable)</li>
      </ul>
      <h3>Process overview</h3>
      <p>The process for generating these documents is focused on being as automated as possible. Below is the general outline of steps.</p>
      <ol>
        <li>Take list of all kernel CVEs</li>
        <li>If the issue is marked as Vendor specific, ignore it.</li>
        <li>Get the Breaking/Fixing Commits. This is retrieved from the internal cache first, if not present it pulls from Ubuntu, Debian, etc to try and fill that information in.</li>
        <li>Using those commit ids, get the first tags in the mainline that they appear.</li>
        <li>Using that version timeline, for each stream that would be vulnerable perform steps 6 through 8.</li>
        <li>Find the commit who has the commit message that matches the commit message from the mainline. This is the fixing commit in that stream.</li>
        <li>Record the commit id and get the earliest tag in the stream which has that commit.</li>
        <li>Output information to stream document.</li>
        <li>Update JSONs.</li>
      </ol>
      <h3>Accuracy</h3>
      <p>The bulk of the data is autogenerated or pulled from other open sources. While every effort is taken to ensure its accuracy, no promise of absolute accuracy can be made. If you think a CVE is missing or is not completely accurate, please fill out an issue to have the data looked at and changed. The eventual goal would be to have a community curated list of CVEs along with when the code was introduced and when it was fixed.</p>
      <h3>Development</h3>
      <p>This project is being actively maintained. To review the project, or contribute, please visit the GitHub repository.</p>
      <v-btn 
        href="https://github.com/nluedtke/linux_kernel_cves"
      >Visit Us on GitHub</v-btn>
    </v-flex>
  </v-layout>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      changes: '',
      dismissedChanges: false,
      errors: []
    }
  },
  created () {
    var changesUrl = this.$apiBaseUrl + 'CHANGES.md'
    axios.get(changesUrl)
      .then(response => {
      // JSON responses are automatically parsed.
        this.changes = response.data
      })
      .catch(e => {
        this.errors.push(e)
      })
  },
  methods: {
    dismissChanges () {
      this.dismissedChanges = true
    },
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.row {
  margin: 1em;
}
</style>
